# configuration.yml

# key:value pairs define instrument-specific configuration

# NOTE: To use any changes to this file, start a NEW session
# after the changes are made.

# instrument settings
DATABROKER_CATALOG: bdp2022

RUNENGINE_METADATA:
  beamline_id: BDP
  instrument_name: APS-U Beamline Data Pipelines project in 2022
  proposal_id: bdp2022
  milestone: BDP M6 demo

# device PVs
IOC_PREFIX_ADPVA: "13PVA1:"
IOC_PREFIX_ADSIM: "bdpSimExample:"
IOC_PREFIX_GP: "bdpgp:"
PV_CA_ADSIM_X_CALC: "bdpgp:userCalc9"
PV_CA_ADSIM_Y_CALC: "bdpgp:userCalc10"
PV_CA_FAST_UPDATE_X_RBV: "bdpgp:gp:float1"
PV_CA_FAST_UPDATE_X_VAL: "bdpgp:gp:float11"
PV_CA_FAST_UPDATE_Y_RBV: "bdpgp:gp:float2"
PV_CA_FAST_UPDATE_Y_VAL: "bdpgp:gp:float12"
PV_CA_HDF5_FILE_NAME: "bdpapi:ImageFileName"
PV_CA_IMAGE_FILE_NAME: "bdpapi:ImageFileName"
PV_CA_INCIDENT_BEAM_SIMULATOR_CALC: "bdpgp:userCalc2"
PV_CA_PZT_X: "bdpgp:gp:float1"
PV_CA_PZT_Y: "bdpgp:gp:float2"
PV_CA_RUN_ENGINE_SCAN_ID: "bdpapi:RunEngine_scan_id"
PV_CA_XY_STAGE_X: "bdpgp:m9"
PV_CA_XY_STAGE_Y: "bdpgp:m10"
PV_PVA_IMAGE: "pvapy:image"

# paths & configuration
BDP_DATA_DIR: /gdata/bdp/BDP/bdp-test-02
BDP_DATA_FILE_NAME: bdp
BDP_DATA_FILE_TEMPLATE: "%s%s_%3.6d.tif"
ADIOC_IMAGE_ROOT: &FILE_PATH /clhome/BDP/voyager
BLUESKY_IMAGE_ROOT: *FILE_PATH
AD_IMAGE_SUBDIR: "adsimdet/%Y/%m/%d/"
IMAGE_RUN_XREF_FILE: xref_image_run.yml

# permissions
ALLOW_AREA_DETECTOR_WARMUP: true
ENABLE_AREA_DETECTOR_IMAGE_PLUGIN: true
APS_IN_BASELINE: true
ENABLE_CALCS: true
USE_PROGRESS_BAR: false

# ----------------------------------

# default timeouts (seconds)
PV_TIMEOUT: &TIMEOUT 9.87654
PV_WRITE_TIMEOUT: *TIMEOUT
PV_CONNECTION_TIMEOUT: *TIMEOUT

# Minimum software package version checks: MAJOR.minor (no .patch).
# These will be converted to tuple() for comparisons.
MINIMUM_PYTHON_VERSION:
  - 3
  - 7
MINIMUM_BLUESKY_VERSION:
  - 1
  - 8
MINIMUM_OPHYD_VERSION:
  - 1
  - 6
MINIMUM_DATABROKER_VERSION:
  - 1
  - 2
