# configuration.yml

# key:value pairs define instrument-specific configuration

# NOTE: To use any changes to this file, start a NEW session
# after the changes are made.

# instrument settings
DATABROKER_CATALOG: bdp2022

RUNENGINE_METADATA:
  beamline_id: BDP
  instrument_name: APS-U Beamline Data Pipelines project in 2022
  proposal_id: bdp2022

# device PVs
ADSIM_IOC_PREFIX: "bdpSimExample:"
GP_IOC_PREFIX: "bdpgp:"
XY_STAGE_X_PV: "bdpgp:m9"
XY_STAGE_Y_PV: "bdpgp:m10"
PZT_X_PV: "bdpgp:gp:float1"
PZT_Y_PV: "bdpgp:gp:float2"
ADSIM_X_CALC_PV: "bdpgp:userCalc9"
ADSIM_Y_CALC_PV: "bdpgp:userCalc10"
INCIDENT_BEAM_SIMULATOR_CALC_PV: "bdpgp:userCalc2"
HDF5_FILE_NAME_PV: bdpapi:ImageFileName
RUN_ENGINE_SCAN_ID_PV: bdpapi:RunEngine_scan_id
FAST_UPDATE_X_VAL: bdpgp:gp:float18
FAST_UPDATE_X_RBV: bdpgp:gp:float8
FAST_UPDATE_Y_VAL: bdpgp:gp:float19
FAST_UPDATE_T_RBV: bdpgp:gp:float9

# paths
#ADIOC_IMAGE_ROOT: /tmp
#BLUESKY_IMAGE_ROOT: /tmp/docker_ioc/iocbdpad/tmp
ADIOC_IMAGE_ROOT: &FILE_PATH /clhome/BDP/voyager
BLUESKY_IMAGE_ROOT: *FILE_PATH
AD_IMAGE_SUBDIR: "adsimdet/%Y/%m/%d/"
IMAGE_RUN_XREF_FILE: xref_image_run.yml

# permissions
ALLOW_AREA_DETECTOR_WARMUP: false
ENABLE_AREA_DETECTOR_IMAGE_PLUGIN: true
APS_IN_BASELINE: true
ENABLE_CALCS: true
USE_PROGRESS_BAR: false

# ----------------------------------

# default timeouts (seconds)
PV_TIMEOUT: &TIMEOUT 60
PV_WRITE_TIMEOUT: *TIMEOUT
PV_CONNECTION_TIMEOUT: *TIMEOUT

# Minimum software package version checks: MAJOR.minor (no .patch).
# These will be converted to tuple() for comparisons.
MINIMUM_PYTHON_VERSION:
  - 3
  - 7
MINIMUM_BLUESKY_VERSION:
  - 1
  - 8
MINIMUM_OPHYD_VERSION:
  - 1
  - 6
MINIMUM_DATABROKER_VERSION:
  - 1
  - 2
